language: java
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info

script:
  - mvn clean verify
  - docker login -u $DOCKER_USER -p $DOCKER_PASS 
  - mvn docker:build
  - docker push etiennek/spring-boot-admin
